services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vivaeventos-notification-service

    ports:
      - "8085:8085"

    environment:
      RABBITMQ_HOST: event-service-rabbitmq
      RABBITMQ_PORT: 5672

      ORDER_SERVICE_URL: http://order-service:8083

      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

    restart: always

    networks:
      - event-network

networks:
  event-network:
    external: true
    name: vivaeventos-event-service_event-network