services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vivaeventos-notification-service
    ports:
      - "8085:8085"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ORDER_SERVICE_URL: http://order-service:8083
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-service-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always